FROM mhart/alpine-node:11 as build

ARG REACT_APP_DATA_HUB_URI
ARG REACT_APP_DATA_HUB_SUBSCRIPTIONS_URI
ARG REACT_APP_KEYCLOAK_URL
ARG REACT_APP_KEYCLOAK_REALM
ARG REACT_APP_DAILYOS_SERVER_URI

WORKDIR /usr/src/app
COPY package.json ./
RUN yarn
COPY . .

ENV PATH /app/node_modules/.bin:$PATH
ENV SKIP_PREFLIGHT_CHECK true
ENV REACT_APP_DATA_HUB_URI $REACT_APP_DATA_HUB_URI 
ENV REACT_APP_DATA_HUB_SUBSCRIPTIONS_URI $REACT_APP_DATA_HUB_SUBSCRIPTIONS_URI 
ENV REACT_APP_KEYCLOAK_URL $REACT_APP_KEYCLOAK_URL
ENV REACT_APP_KEYCLOAK_REALM $REACT_APP_KEYCLOAK_REALM
ENV REACT_APP_DAILYOS_SERVER_URI $REACT_APP_DAILYOS_SERVER_URI

RUN yarn build

FROM nginx:1.15.2-alpine
COPY --from=build /usr/src/app/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
