/* eslint-disable no-undef */
/* eslint-disable spaced-comment */
/// <reference types="cypress" />

context('suppliers module | inventory app', () => {
   const newSupplierName = 'delete this supplier'

   beforeEach(() => {
      cy.visit('/apps/inventory')
         .get('h2')
         .contains('Suppliers')
         .click()
         .wait(2000)
   })

   it('should load suppliers listings view', () => {
      cy.get('.tabulator-header').should('be.visible')
   })

   it('should create a supplier and change his name', () => {
      cy.get('[data-testid="addSupplier"]')
         .click()
         .get('input[name="supplierName"]')
         .should('contain.value', 'supplier')
         .clear()
         .type(newSupplierName)
         .blur()
         .wait(1000)
         .should('contain.value', newSupplierName)
   })

   it('should open the created supplier form and update his address', () => {
      cy.get('input[type="search"]')
         .type(newSupplierName)
         .wait(500)
         .get('div.tabulator-cell')
         .then(e => e[0])
         .click()
         .wait(1000)
         .get('[data-testid="supplier_address"]')
         .click()
         .get('label[for="label"]')
         .click()
         .wait(100)
         .get('input#address1')
         .type('Address line 1 test')
         .get('input#address2')
         .type('Address line 2 test')
         .get('input#city')
         .type('test city name')
         .get('input#zip')
         .type('823402')
         .get('input#instructions')
         .type('some instruction goes here...')
         .get('button')
         .contains('Save')
         .click()
         .wait(200)
         .get('span')
         .should('contain', '823402')
   })

   it('should open the created supplier and update his contact information', () => {
      cy.get('input[type="search"]')
         .type(newSupplierName)
         .wait(500)
         .get('div.tabulator-cell')
         .then(e => e[0])
         .click()
         .wait(1000)
         .get('[data-testid="supplier_contact"]')
         .click()
         .get('input#firstName')
         .type('Cypress')
         .get('input#lastName')
         .type('user')
         .get('input#email')
         .type('test@test.com')
         .get('input[type="tel"]')
         .clear()
         .type('911234567890')
         .get('button')
         .contains('Save')
         .click()
         .wait(200)
         .get('span')
         .should('contain', 'Cypress user')
   })

   it('should get the created supplier and try to delete him', () => {
      cy.get('input[type="search"]')
         .type(newSupplierName)
         .wait(500)
         .get('div.formatterCell > svg')
         .then(e => e[0])
         .click()
         .get('.Toastify__toast')
         .contains('Supplier deleted!')
   })
})
