import { CREATE_SUPPLIER, UPDATE_SUPPLIER, DELETE_SUPPLIER } from './mutations'
import { SUPPLIERS, SUPPLIER } from './queries'

export {
   CREATE_SUPPLIER,
   UPDATE_SUPPLIER,
   DELETE_SUPPLIER,
   SUPPLIERS,
   SUPPLIER,
}
