import {
   MASTER_PROCESSINGS,
   MASTER_ALLERGENS,
   SUPPLIERS,
   SUPPLIER,
} from './queries'

import { CREATE_SUPPLIER, UPDATE_SUPPLIER, DELETE_SUPPLIER } from './mutations'

export {
   CREATE_SUPPLIER,
   UPDATE_SUPPLIER,
   DELETE_SUPPLIER,
   SUPPLIERS,
   SUPPLIER,
   MASTER_PROCESSINGS,
   MASTER_ALLERGENS,
}
