import { RECIPES, PRODUCTS, COLLECTIONS, ACCOMPANIMENT_TYPES } from './queries'

import {
   CREATE_PRODUCT,
   UPDATE_PRODUCT,
   UPDATE_COLLECTION,
   CREATE_COLLECTION,
} from './mutations/'

export {
   RECIPES,
   ACCOMPANIMENT_TYPES,
   CREATE_PRODUCT,
   UPDATE_PRODUCT,
   PRODUCTS,
   CREATE_COLLECTION,
   UPDATE_COLLECTION,
   COLLECTIONS,
}
