import { RECIPES, PRODUCTS, COLLECTIONS, ACCOMPANIMENT_TYPES } from './queries'

import {
   CREATE_PRODUCT,
   UPDATE_PRODUCT,
   CREATE_SIMPLE_RECIPE_PRODUCT,
   CREATE_SIMPLE_RECIPE_PRODUCT_OPTIONS,
   UPDATE_COLLECTION,
   CREATE_COLLECTION,
} from './mutations/'

export {
   RECIPES,
   ACCOMPANIMENT_TYPES,
   CREATE_PRODUCT,
   UPDATE_PRODUCT,
   PRODUCTS,
   CREATE_COLLECTION,
   UPDATE_COLLECTION,
   COLLECTIONS,
   CREATE_SIMPLE_RECIPE_PRODUCT,
   CREATE_SIMPLE_RECIPE_PRODUCT_OPTIONS,
}
