import { CUSTOMERS_COUNT, TOTAL_REVENUE } from './subscriptions'
import {
   CUSTOMERS_LISTING,
   CUSTOMER_DATA,
   ORDERS_LISTING,
   ORDER,
   ALL_DATA,
} from './queries'

export {
   CUSTOMERS_COUNT,
   TOTAL_REVENUE,
   CUSTOMERS_LISTING,
   CUSTOMER_DATA,
   ORDERS_LISTING,
   ORDER,
   ALL_DATA,
}
